# Generated by Django 4.2 on 2023-04-26 03:25

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contractors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrator',
            name='country',
            field=django_countries.fields.CountryField(max_length=2, verbose_name='Country Name'),
        ),
    ]
