# Generated by Django 4.2 on 2023-04-26 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contractors', '0003_rename_contrator_contractor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Country',
        ),
    ]
