# Generated by Django 4.2 on 2023-05-02 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractors', '0006_country'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.AlterField(
            model_name='contractor',
            name='country',
            field=models.CharField(max_length=30, verbose_name='Country Name'),
        ),
    ]
